version: "3.9"

services:

  mapfish:
    build: pdf_map_export/.
    ports:
      - "8080:8080"

  backend:
    build:
      context: python_program/.
    ports:
      - "5000:5000"
    depends_on:
      - mapfish

  webinterface:
    build:
      context: webinterface/.
      args:
        # By default, we build in productive mode. You can change the build mode by specifying $ANGULAR_CONFIGURATION.
        - configuration=${ANGULAR_CONFIGURATION:-production}
    ports:
      - "80:80"
    depends_on:
      - backend
