templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: report.jrxml
    attributes:
      map: !map
        maxDpi: 400
        width: 813
        height: 566
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}
    - !createScalebar {}

